# SwarmCD configuration file refernce

# The interval in seconds that SwarmCD 
# waits everytime before pulling 
update_interval: 120

# The path where SwarmCD will checkout repos
repos_path: repos/

# Automatically detect secrets to decrypt with SOPS
sops_secrets_discovery: true

# Automatically rotate configs and secrets
# when the change. Adds a hash to config
# and secret names
auto_rotate: true

# You can define repos here instead of 
# defining a separate repos.yaml file
repos:

# You can define stacks here instead of 
# defining a separate stacks.yaml file
stacks:

# The WEB UI address
address: 0.0.0.0:8080

# If you need the same values on every stack (domain names),
# you can define global values here instead of global_values.yaml file
# They can be overridden in the values file at stack level.
global_values:
